### ISSUE TITLE
Pre-load list of hooks

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-parser-nmea0183#102]
Ref. https://github.com/SignalK/signalk-parser-nmea0183/commit/dd98b6619f1bc206f750bdf5718102c864325c6c#commitcomment-25275242 One solution would be to load all mappings on start like https://github.com/SignalK/n2k-signalk/blob/master/n2kMappings.js

**Comment by tkurki** [comment]
The real problem is https://github.com/SignalK/signalk-parser-nmea0183/blob/18aeb64906a895fea90aa6939cbb076f715117fd/lib/findHook.js#L27 which does a synchronous file system per each line.
