### ISSUE TITLE
AIS - VDM Navigation state. Not released?

### ISSUE THREAD

**Issue by Hakansv** [SignalK/signalk-parser-nmea0183#161]
@tkurki 
The navigation state value e.g. "anchored" seems to not reflect actual status. I assume the value is not updated/released once set as long as one target is present in the "data base"?
My example here is the ship Oljaren. Here on the first shot you can see the anchorage state is set although it is not set in data coming in to SK. If I compare to what's streaming out via the TCP connection, i.e. a direct reflection of incoming data, the anchorage state is not. set.
Since the ship Oljaren was really anchored some 15 minutes before the actual shots I assume the state "anchored" is correctly set but not released when the VDM sentence no longer contain that info. Could my theory be correct?
If I let the SK data base be cleaned out from Oljaren, by another data stream, and restart the previous data stream Oljaren does not have state "anchored" until it is actually set. And then again it's never released.

![bild](https://user-images.githubusercontent.com/7202854/74103053-475a0880-4b49-11ea-952c-64bb0c05ae03.png)

Signal K connection:
![bild](https://user-images.githubusercontent.com/7202854/74102786-2690b380-4b47-11ea-8c77-c08f103f0477.png)

TCP connection:
![bild](https://user-images.githubusercontent.com/7202854/74102809-5770e880-4b47-11ea-931b-3294c77d44f6.png)

**Comment by sbender9** [comment]
Yep. We have a bug, looks like the real problem is that nav status code 0 does not work. 

I’ll get a fix in today.

**Comment by Hakansv** [comment]
Very good!
Thanks for your prompt action.
I'll make test whenever available.
