### ISSUE TITLE
Performance problems caused by clone

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#30]
The parser clones the whole in memory object tree for each `change` event even if this data is never used by anything in the current server, as the server uses a separate Multiplexer to accumulate the tree from all sources.

The clone operation is heavy, especially so if there is a lot of data like when you have AIS data. 

By changing Multiplexer.retrieve() to return the original tree I get about 10 times the throughput.

Some fix is needed for this. Everything would be a lot simpler if the parser did not use a Multiplexer at all but just emitted delta messages generated directly in the codec. If one should want to generate the tree one could just pipe the delta output to a Multiplexer, just like the server does.

Furthermore in case of AIS we will need to prune two trees, the one inside nmea0182 parser and the one in the server. Sounds like a lot of work to me.

Suggestions:
- retrieve() never clones but returns the original tree
- change the logic so that if there are no listeners that need the tree do not generate the events (there aren't any in the current server implementation)
- change the current parser API so that Transformer outputs delta instead of tree and remove the `sentence` and `signalk`events, as I believe these are not used anywhere. This would remove the need for the retrieve() call.

@fabdrol your thoughts?

**Comment by tkurki** [comment]
This problem is further aggravated by the fact that each VDM message causes three `change`events, so three clone operations...

**Comment by fabdrol** [comment]
@tkurki sorry for my late reply, I have known about this issue for a while - it's mainly due to the fact that the initial version was a much more fully-featured program (to be used stand-alone) before I started work on saildata-server. 
I started on a much smaller parser, which only outputs delta and doesn't keep a tree in memory. Shouldn't take too long to complete, in between everything.

**Comment by tkurki** [comment]
Fixed by 83fea90bcc99c8809c37f278fe8a4c54917a27fe
