### ISSUE TITLE
SI units

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#38]
Signal K specification states SI units and nmea0183 parser must be updated to produce SI units.

**Comment by philgutowski** [comment]
@tkurki mind giving a bit more detail about what needs to be changed?

**Comment by tkurki** [comment]
Sure. We recently made the move to use SI units in Signal K. In practice this means that some of the quantities need to be changed so that they are using the correct units. 

A practical example is that angles and directions are currently in degrees in signalk-parser-nmea0183. They need to be converted to radians.

All in all the parser's conversions from nmea0183 need to be checked so that they are in correct units.

See https://github.com/SignalK/specification/blob/master/keyswithmetadata.json

**Comment by tkurki** [comment]
Ping @fabdrol

**Comment by philgutowski** [comment]
Here's a start... https://github.com/SignalK/signalk-parser-nmea0183/pull/39

**Comment by tkurki** [comment]
Closed by #41
