### ISSUE TITLE
Name from AIS static data should produce delta with empty path

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#43]
https://github.com/SignalK/specification/pull/157#issuecomment-178089729

https://github.com/SignalK/specification/blob/4bd476f05749b62d88ccb43a29fa8290c6bd6884/test/fullsignalk.js#L102-L126

**Comment by fabdrol** [comment]
This is in there (https://github.com/SignalK/signalk-parser-nmea0183/blob/development/hooks/VDM.js), closing.
