### ISSUE TITLE
RMB support

### ISSUE THREAD

**Issue by fbeauche** [SignalK/signalk-parser-nmea0183#81]
Im new to SignalK and stuff, but would it make sense to have support for "[RMB - Recommended Minimum Navigation Information](http://www.catb.org/gpsd/NMEA.html#_rmb_recommended_minimum_navigation_information)"  at some point ?

I would be willing to try to make a pull request  if it makes sense. 

My plan is to have OpenPlotter send waypoint information and display it on a web dashboard along with COG so i can make sure  im going to my waypoint ! ( no fancy autopilot ;) )

**Comment by fabdrol** [comment]
@fbeauche sounds good, if you do a PR have a look at the `development` branch, let me know if you run into any issues.

**Comment by joabakk** [comment]
Closed by #82?
