### ISSUE TITLE
Add support for more sentence types. 

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-parser-nmea0183#9]
Currently, parser supports the following sentence types: `APB`, `BWC`, `DBT`, `GGA`, `GLL`, `MWV`, `RMC`, `VTG` and I started work on codecs for `VDM`, `GBS`, `GSA`, `GSV` and `VDO`. It doesn't take a lot of time to create codecs, but the more the merrier, so all help is welcome.

**Comment by joabakk** [comment]
If I want to help, can I just create codecs, test like described above and pull?

**Comment by tkurki** [comment]
Yes! What sentences do you have in mind?

**Comment by joabakk** [comment]
Well I am thinking of ROT, RPM, VDR, VPW and VWR. These are all described in pynmea2 (github) and I am using these in my current python based calculations. Basically I am looking to see if I have fairly current values for wind relative, boat speed, rate of turn and that the engine is off. Then I look to see if the boat is turning (ROT) and if not, I am comparing boat speed with a database to see if I am sailing close to optimal speed or if I need to update the database (polar diagram). I am not even sure it´s best to port the calculation to node js, but I´d like to use signal K for the values I have and for the ones I calculate, as far as possible.

**Comment by joabakk** [comment]
When I enter your example, I get "TypeError: Property 'decode' of object #<Object> is not a function" on the last line.

**Comment by tkurki** [comment]
I think Rabian's comment above was not related to this. 

The simplest way to add a codec is to copy a simple one, for example DBT.js, modify it and add it to https://github.com/SignalK/signalk-parser-nmea0183/blob/master/codecs/index.js.

If I were you I'd start by creating a test under `test` directory. DBT is a good example because there's an individual test file for it as well that you can use as a sample.

**Comment by joabakk** [comment]
Sorry to bother you again. I have added ROT and RPM to my test fork, added these to codecs/index.js and used DBT as example. It seems the parser.on('delta', function(delta) { -function is not working properly and I get timeouts in mocha. Have I forgotten something?

**Comment by tkurki** [comment]
You can open a PR to show your code even if it is not ready for merging. Or do you have the code in your own repo?

**Comment by joabakk** [comment]
opened a PR. If I could get some help sorting that out, I can continue and hopefully contribute

**Comment by joabakk** [comment]
How do we think of proprietary sentences? I would like to add PSILTBS (target boat speed, Silva Nexus/Garmin sentence). Also, there are some ok sentences that are marked as obsolete from NMEA, but they are more specific than say XDR, so easier to implement.

**Comment by tkurki** [comment]
If you need them go right ahead and add.

**Comment by tkurki** [comment]
Closing as too generic
